name: CI
on: push
jobs:

  lint_and_typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: poetry install
        run: poetry install --no-interaction --extras=training

      - name: black
        run: poetry run black --check .

      - name: lint
        run: poetry run ruff check .

      - name: typecheck
        run: poetry run pyright
